[build]
  functions = "functions"

[[redirects]]
  from = "/upload_complete"
  to = "/.netlify/functions/upload_complete"
  status = 200

[[redirects]]
  from = "/upload_incomplete"
  to = "/.netlify/functions/upload_incomplete"
  status = 200
